{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "OWNER = \"dronekit\"\n",
    "REPO = \"dronekit-python\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "success!\n",
      "[{'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1074', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1074/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1074/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1074/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1074', 'id': 724567391, 'node_id': 'MDU6SXNzdWU3MjQ1NjczOTE=', 'number': 1074, 'title': 'Dronekit - Control each waypoint in ongoing mission items:', 'user': {'login': 'msmohanbabu', 'id': 1754758, 'node_id': 'MDQ6VXNlcjE3NTQ3NTg=', 'avatar_url': 'https://avatars3.githubusercontent.com/u/1754758?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/msmohanbabu', 'html_url': 'https://github.com/msmohanbabu', 'followers_url': 'https://api.github.com/users/msmohanbabu/followers', 'following_url': 'https://api.github.com/users/msmohanbabu/following{/other_user}', 'gists_url': 'https://api.github.com/users/msmohanbabu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/msmohanbabu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/msmohanbabu/subscriptions', 'organizations_url': 'https://api.github.com/users/msmohanbabu/orgs', 'repos_url': 'https://api.github.com/users/msmohanbabu/repos', 'events_url': 'https://api.github.com/users/msmohanbabu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/msmohanbabu/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-10-19T12:32:13Z', 'updated_at': '2020-10-19T12:32:13Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Team, I am trying to use position_ned in each waypoint of the mission. to bring down the drone for certain metres and hover for few seconds and back on mission. I cannot hold the mission for each waypoint.. anyone come across this issue?', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1072', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1072/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1072/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1072/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1072', 'id': 710812202, 'node_id': 'MDU6SXNzdWU3MTA4MTIyMDI=', 'number': 1072, 'title': 'map not visible', 'user': {'login': 'prashanthravi19', 'id': 58167271, 'node_id': 'MDQ6VXNlcjU4MTY3Mjcx', 'avatar_url': 'https://avatars1.githubusercontent.com/u/58167271?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/prashanthravi19', 'html_url': 'https://github.com/prashanthravi19', 'followers_url': 'https://api.github.com/users/prashanthravi19/followers', 'following_url': 'https://api.github.com/users/prashanthravi19/following{/other_user}', 'gists_url': 'https://api.github.com/users/prashanthravi19/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/prashanthravi19/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/prashanthravi19/subscriptions', 'organizations_url': 'https://api.github.com/users/prashanthravi19/orgs', 'repos_url': 'https://api.github.com/users/prashanthravi19/repos', 'events_url': 'https://api.github.com/users/prashanthravi19/events{/privacy}', 'received_events_url': 'https://api.github.com/users/prashanthravi19/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-29T06:40:40Z', 'updated_at': '2020-09-29T06:45:32Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'map is not visible in drone delivery app what needs to be changed\\r\\n![dronetrack](https://user-images.githubusercontent.com/58167271/94522536-70044f00-024d-11eb-924a-b8c13aaf756c.png)\\r\\n', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1071', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1071/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1071/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1071/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1071', 'id': 710774166, 'node_id': 'MDU6SXNzdWU3MTA3NzQxNjY=', 'number': 1071, 'title': 'drone delivery code stops in polled mode guided', 'user': {'login': 'prashanthravi19', 'id': 58167271, 'node_id': 'MDQ6VXNlcjU4MTY3Mjcx', 'avatar_url': 'https://avatars1.githubusercontent.com/u/58167271?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/prashanthravi19', 'html_url': 'https://github.com/prashanthravi19', 'followers_url': 'https://api.github.com/users/prashanthravi19/followers', 'following_url': 'https://api.github.com/users/prashanthravi19/following{/other_user}', 'gists_url': 'https://api.github.com/users/prashanthravi19/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/prashanthravi19/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/prashanthravi19/subscriptions', 'organizations_url': 'https://api.github.com/users/prashanthravi19/orgs', 'repos_url': 'https://api.github.com/users/prashanthravi19/repos', 'events_url': 'https://api.github.com/users/prashanthravi19/events{/privacy}', 'received_events_url': 'https://api.github.com/users/prashanthravi19/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-29T05:28:15Z', 'updated_at': '2020-09-29T05:28:15Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'While running the drone delivery app the polled mode stops in guided and it continues to repeat command without moving froward', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1070', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1070/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1070/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1070/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1070', 'id': 710423333, 'node_id': 'MDU6SXNzdWU3MTA0MjMzMzM=', 'number': 1070, 'title': \"dronekit doesn't change flight modes - DO_SET_MODE: UNSUPPORTED\", 'user': {'login': 'EmirhanKarahan', 'id': 48404459, 'node_id': 'MDQ6VXNlcjQ4NDA0NDU5', 'avatar_url': 'https://avatars3.githubusercontent.com/u/48404459?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/EmirhanKarahan', 'html_url': 'https://github.com/EmirhanKarahan', 'followers_url': 'https://api.github.com/users/EmirhanKarahan/followers', 'following_url': 'https://api.github.com/users/EmirhanKarahan/following{/other_user}', 'gists_url': 'https://api.github.com/users/EmirhanKarahan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/EmirhanKarahan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/EmirhanKarahan/subscriptions', 'organizations_url': 'https://api.github.com/users/EmirhanKarahan/orgs', 'repos_url': 'https://api.github.com/users/EmirhanKarahan/repos', 'events_url': 'https://api.github.com/users/EmirhanKarahan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/EmirhanKarahan/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-28T16:47:57Z', 'updated_at': '2020-09-28T16:51:16Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'using dronekit-sitl, mavproxy and dronekit library. tried on ubuntu 16,18,20 and debian same problem.\\r\\n\\r\\nim starting the code (simple_goto example) but the altitude doesn\\'t change. if i check mavproxy terminal i see the error \"DO_SET_MODE: UNSUPPORTED\". if i change the mode stabilize to guided manually from mission planner, drone takes off and does the mission until the landing point. drone doesn\\'t land because it\\'s not able to change mode.\\r\\n\\r\\nthank you', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1069', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1069/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1069/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1069/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1069', 'id': 710236670, 'node_id': 'MDU6SXNzdWU3MTAyMzY2NzA=', 'number': 1069, 'title': 'error on trying to run drone await set(types) invalid syntax error', 'user': {'login': 'prashanthravi19', 'id': 58167271, 'node_id': 'MDQ6VXNlcjU4MTY3Mjcx', 'avatar_url': 'https://avatars1.githubusercontent.com/u/58167271?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/prashanthravi19', 'html_url': 'https://github.com/prashanthravi19', 'followers_url': 'https://api.github.com/users/prashanthravi19/followers', 'following_url': 'https://api.github.com/users/prashanthravi19/following{/other_user}', 'gists_url': 'https://api.github.com/users/prashanthravi19/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/prashanthravi19/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/prashanthravi19/subscriptions', 'organizations_url': 'https://api.github.com/users/prashanthravi19/orgs', 'repos_url': 'https://api.github.com/users/prashanthravi19/repos', 'events_url': 'https://api.github.com/users/prashanthravi19/events{/privacy}', 'received_events_url': 'https://api.github.com/users/prashanthravi19/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 3, 'created_at': '2020-09-28T12:50:02Z', 'updated_at': '2020-10-01T07:36:23Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'i get an error while trying to run drone delivery.py how can the bug be resolved?\\r\\n await = set(types)\\r\\n          ^\\r\\nSyntaxError: invalid syntax\\r\\nfull stack trace\\r\\nTraceback (most recent call last):\\r\\n  File \"drone_delivery.py\", line 18, in <module>\\r\\n    from dronekit import connect, VehicleMode, LocationGlobal, LocationGlobalRelative\\r\\n  File \"C:\\\\Users\\\\Prashanth\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python38\\\\lib\\\\site-packages\\\\dronekit\\\\__init__.py\", line 2192\\r\\n    await = set(types)\\r\\n          ^\\r\\nSyntaxError: invalid syntax', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1068', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1068/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1068/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1068/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1068', 'id': 708649209, 'node_id': 'MDU6SXNzdWU3MDg2NDkyMDk=', 'number': 1068, 'title': 'Navio2 + PS4 Controller + Custom functions', 'user': {'login': 'Benix6', 'id': 48918803, 'node_id': 'MDQ6VXNlcjQ4OTE4ODAz', 'avatar_url': 'https://avatars1.githubusercontent.com/u/48918803?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Benix6', 'html_url': 'https://github.com/Benix6', 'followers_url': 'https://api.github.com/users/Benix6/followers', 'following_url': 'https://api.github.com/users/Benix6/following{/other_user}', 'gists_url': 'https://api.github.com/users/Benix6/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Benix6/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Benix6/subscriptions', 'organizations_url': 'https://api.github.com/users/Benix6/orgs', 'repos_url': 'https://api.github.com/users/Benix6/repos', 'events_url': 'https://api.github.com/users/Benix6/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Benix6/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-25T05:20:41Z', 'updated_at': '2020-09-25T05:21:52Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Hello,\\r\\n\\r\\nI am new to dronekit and couldn‘t find anything in regard to this topic.\\r\\n\\r\\nIs it possible to connect a Bluetooth ps4 controller to the raspberry pi and write a python - dronekit script that allows me to \\r\\n1) use ardupilot Auto stabilize feature that the drone stays stable in air\\r\\n2) set controller inputs like L2=decline(less throttle), R2=Climb(more throttle), left stick=lean (forward, backwards,...), right stick=change direction (compass) and say x=play sound from onboard speaker\\r\\n\\r\\nI am using a raspberry pi 4 with navio2 and I don’t want to use a groundstation but use the sensors of navio and flight features from ardupilot with custom setup.\\r\\nIs that possible and if yes, is there any template/tutorial for that?\\r\\n\\r\\nThanks in advance', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1066', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1066/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1066/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1066/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1066', 'id': 707058301, 'node_id': 'MDU6SXNzdWU3MDcwNTgzMDE=', 'number': 1066, 'title': 'ERROR:autopilot:ARMING MOTORS', 'user': {'login': 'atomattias', 'id': 24213287, 'node_id': 'MDQ6VXNlcjI0MjEzMjg3', 'avatar_url': 'https://avatars0.githubusercontent.com/u/24213287?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/atomattias', 'html_url': 'https://github.com/atomattias', 'followers_url': 'https://api.github.com/users/atomattias/followers', 'following_url': 'https://api.github.com/users/atomattias/following{/other_user}', 'gists_url': 'https://api.github.com/users/atomattias/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/atomattias/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/atomattias/subscriptions', 'organizations_url': 'https://api.github.com/users/atomattias/orgs', 'repos_url': 'https://api.github.com/users/atomattias/repos', 'events_url': 'https://api.github.com/users/atomattias/events{/privacy}', 'received_events_url': 'https://api.github.com/users/atomattias/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 2, 'created_at': '2020-09-23T05:27:32Z', 'updated_at': '2020-10-05T16:44:59Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Help me out, I am new to Dronekit-python, My goal is to use dronekit python on sitl. \\r\\nMy system is ubuntu 18.04\\r\\nI am running  _$dronekit-sitl copter_ in one terminal and tried to connect with it from another. \\r\\nI test it with the sample script.\\r\\n_$python simple_goto.py_\\r\\nBut it looks like it is not changing mode and is failed as it tried to arm the motor.\\r\\n\\r\\n\\r\\n\\r\\n\\r\\n![Uploading drone.png…]()\\r\\n![drone](https://user-images.githubusercontent.com/24213287/94005918-b4a06e00-fda7-11ea-81c2-542920c96f82.jpg)\\r\\n', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1065', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1065/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1065/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1065/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1065', 'id': 705637135, 'node_id': 'MDU6SXNzdWU3MDU2MzcxMzU=', 'number': 1065, 'title': 'Connecting to a Vehicle in a Multi Vehicle Link', 'user': {'login': 'mustafa-gokce', 'id': 48911620, 'node_id': 'MDQ6VXNlcjQ4OTExNjIw', 'avatar_url': 'https://avatars0.githubusercontent.com/u/48911620?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mustafa-gokce', 'html_url': 'https://github.com/mustafa-gokce', 'followers_url': 'https://api.github.com/users/mustafa-gokce/followers', 'following_url': 'https://api.github.com/users/mustafa-gokce/following{/other_user}', 'gists_url': 'https://api.github.com/users/mustafa-gokce/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mustafa-gokce/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mustafa-gokce/subscriptions', 'organizations_url': 'https://api.github.com/users/mustafa-gokce/orgs', 'repos_url': 'https://api.github.com/users/mustafa-gokce/repos', 'events_url': 'https://api.github.com/users/mustafa-gokce/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mustafa-gokce/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-21T14:13:35Z', 'updated_at': '2020-09-21T14:13:35Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Hi.\\r\\nI am using RFD900x telemetry modules to connect multiple vehicles one by one.\\r\\nI am using the the following commands.\\r\\nTo connect to telemetry:\\r\\nmavproxy.exe --master=COM256,57600 --out=127.0.0.1:10000 --out=127.0.0.1:10010 --out=127.0.0.1:10020 --out=127.0.0.1:10030 --cmd=\"set shownoise false\" --daemon\\r\\nTo connect and distribute vehicle one by one:\\r\\nmavproxy.exe --master=udpin:127.0.0.1:10010 --target-system=10 --cmd=\"set shownoise false\" --out=127.0.0.1:20010\\r\\nmavproxy.exe --master=udpin:127.0.0.1:10020 --target-system=20 --cmd=\"set shownoise false\" --out=127.0.0.1:20020\\r\\nmavproxy.exe --master=udpin:127.0.0.1:10030 --target-system=30 --cmd=\"set shownoise false\" --out=127.0.0.1:20030\\r\\nI assumed that above commands only outputs the target systems one by one but it is not.\\r\\nWhen i try to connect the vehicles using below lines of codes:\\r\\nvehicle1 = connect(\\'127.0.0.1:20010\\', wait_ready=True)\\r\\nvehicle2 = connect(\\'127.0.0.1:20020\\', wait_ready=True)\\r\\nvehicle3 = connect(\\'127.0.0.1:20030\\', wait_ready=True)\\r\\nThe incoming and outgoing data traffic is mixing and there is no target_system parameter for connect() function.\\r\\nHow can i connect vehicles one by one without mixing them up?\\r\\nThanks...', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1064', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1064/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1064/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1064/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1064', 'id': 702783344, 'node_id': 'MDU6SXNzdWU3MDI3ODMzNDQ=', 'number': 1064, 'title': 'home_location is None even though I have location.global_relative_frame data', 'user': {'login': 'shacharp', 'id': 49400601, 'node_id': 'MDQ6VXNlcjQ5NDAwNjAx', 'avatar_url': 'https://avatars2.githubusercontent.com/u/49400601?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/shacharp', 'html_url': 'https://github.com/shacharp', 'followers_url': 'https://api.github.com/users/shacharp/followers', 'following_url': 'https://api.github.com/users/shacharp/following{/other_user}', 'gists_url': 'https://api.github.com/users/shacharp/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/shacharp/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/shacharp/subscriptions', 'organizations_url': 'https://api.github.com/users/shacharp/orgs', 'repos_url': 'https://api.github.com/users/shacharp/repos', 'events_url': 'https://api.github.com/users/shacharp/events{/privacy}', 'received_events_url': 'https://api.github.com/users/shacharp/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-16T13:49:27Z', 'updated_at': '2020-09-16T13:50:13Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Hey,\\r\\n\\r\\nI\\'m not sure what home_location is for, and if I need to wait until this bulk of code is done before continue reading data from the Pixhawk:\\r\\n\\r\\nwhile not vehicle.home_location:\\r\\n    cmds = vehicle.commands\\r\\n    cmds.download()\\r\\n    cmds.wait_ready()\\r\\n    if not vehicle.home_location:\\r\\n        print(\" Waiting for home location ...\")\\r\\nprint(\"\\\\n Home location: %s\" % vehicle.home_location)\\r\\n\\r\\n[https://dronekit-python.readthedocs.io/en/latest/examples/vehicle_state.html]\\r\\n\\r\\nThe documentation says:\\r\\n\"The attribute has a value of None until Vehicle.commands() has been downloaded and the autopilot has set an initial home location (typically where the vehicle first gets GPS lock).\"\\r\\n\\r\\nSo how can it be that I have GPS location, but I\\'m stuck in this infinite loop because vehicle.home_location is None?\\r\\n\\r\\nThanks', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1063', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1063/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1063/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1063/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1063', 'id': 702617887, 'node_id': 'MDU6SXNzdWU3MDI2MTc4ODc=', 'number': 1063, 'title': 'Interupt ongoing dronekit program', 'user': {'login': 'rekhyzakaria55', 'id': 60639340, 'node_id': 'MDQ6VXNlcjYwNjM5MzQw', 'avatar_url': 'https://avatars2.githubusercontent.com/u/60639340?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rekhyzakaria55', 'html_url': 'https://github.com/rekhyzakaria55', 'followers_url': 'https://api.github.com/users/rekhyzakaria55/followers', 'following_url': 'https://api.github.com/users/rekhyzakaria55/following{/other_user}', 'gists_url': 'https://api.github.com/users/rekhyzakaria55/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rekhyzakaria55/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rekhyzakaria55/subscriptions', 'organizations_url': 'https://api.github.com/users/rekhyzakaria55/orgs', 'repos_url': 'https://api.github.com/users/rekhyzakaria55/repos', 'events_url': 'https://api.github.com/users/rekhyzakaria55/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rekhyzakaria55/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-16T09:45:08Z', 'updated_at': '2020-09-16T09:45:08Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Hello,\\r\\nhello, I was wondering if the ongoing mission can be changed or canceled via dronekit? can someone tell me how to do it, please.', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1062', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1062/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1062/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1062/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1062', 'id': 702206932, 'node_id': 'MDU6SXNzdWU3MDIyMDY5MzI=', 'number': 1062, 'title': 'Drone Tech | sd', 'user': {'login': 'sauravDutt', 'id': 38371548, 'node_id': 'MDQ6VXNlcjM4MzcxNTQ4', 'avatar_url': 'https://avatars1.githubusercontent.com/u/38371548?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sauravDutt', 'html_url': 'https://github.com/sauravDutt', 'followers_url': 'https://api.github.com/users/sauravDutt/followers', 'following_url': 'https://api.github.com/users/sauravDutt/following{/other_user}', 'gists_url': 'https://api.github.com/users/sauravDutt/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sauravDutt/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sauravDutt/subscriptions', 'organizations_url': 'https://api.github.com/users/sauravDutt/orgs', 'repos_url': 'https://api.github.com/users/sauravDutt/repos', 'events_url': 'https://api.github.com/users/sauravDutt/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sauravDutt/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-15T19:42:51Z', 'updated_at': '2020-09-15T19:54:37Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'DroneKit-Python library for communicating with Drones via MAVLink.', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1061', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1061/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1061/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1061/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1061', 'id': 700415542, 'node_id': 'MDU6SXNzdWU3MDA0MTU1NDI=', 'number': 1061, 'title': 'Is there a method to direct a drone to go into a specific direction without a waypoint?', 'user': {'login': 'Mytre', 'id': 35982669, 'node_id': 'MDQ6VXNlcjM1OTgyNjY5', 'avatar_url': 'https://avatars3.githubusercontent.com/u/35982669?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Mytre', 'html_url': 'https://github.com/Mytre', 'followers_url': 'https://api.github.com/users/Mytre/followers', 'following_url': 'https://api.github.com/users/Mytre/following{/other_user}', 'gists_url': 'https://api.github.com/users/Mytre/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Mytre/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Mytre/subscriptions', 'organizations_url': 'https://api.github.com/users/Mytre/orgs', 'repos_url': 'https://api.github.com/users/Mytre/repos', 'events_url': 'https://api.github.com/users/Mytre/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Mytre/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-12T23:30:13Z', 'updated_at': '2020-09-12T23:30:13Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Just wanted to know if this was a thing, it seems that the only command I see is simple goto, but this is using coordinates, so I cannot for example tell the rover to just go to left , right, (or north, south, etc) for a set distance.  \\r\\n\\r\\nIs there a function that would allow this in drone kit?', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1058', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1058/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1058/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1058/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1058', 'id': 695157000, 'node_id': 'MDU6SXNzdWU2OTUxNTcwMDA=', 'number': 1058, 'title': 'Dronekit-Sitl \" Error Disarming Motors \"', 'user': {'login': 'drnayeem', 'id': 51094060, 'node_id': 'MDQ6VXNlcjUxMDk0MDYw', 'avatar_url': 'https://avatars0.githubusercontent.com/u/51094060?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/drnayeem', 'html_url': 'https://github.com/drnayeem', 'followers_url': 'https://api.github.com/users/drnayeem/followers', 'following_url': 'https://api.github.com/users/drnayeem/following{/other_user}', 'gists_url': 'https://api.github.com/users/drnayeem/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/drnayeem/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/drnayeem/subscriptions', 'organizations_url': 'https://api.github.com/users/drnayeem/orgs', 'repos_url': 'https://api.github.com/users/drnayeem/repos', 'events_url': 'https://api.github.com/users/drnayeem/events{/privacy}', 'received_events_url': 'https://api.github.com/users/drnayeem/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 7, 'created_at': '2020-09-07T14:26:39Z', 'updated_at': '2020-09-09T06:59:39Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Hello\\r\\n\\r\\nI am trying to connect to SITL.\\r\\nThe connect string works fine.\\r\\nBut when i try to send \\r\\nvehicle.armed = True \\r\\ncommand to arm the quad \\r\\n\\r\\nError: autopilot : ARMING MOTORS\\r\\nCRITICAL: autopilot : GROUND  START\\r\\nCRITICAL: autopilot : Initializing APM...\\r\\nERROR: autopilot : DISARMING MOTORS\\r\\n\\r\\nthis is what i get \\r\\nam Running python 2.7 on a Windows10 PC\\r\\n\\r\\n', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1057', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1057/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1057/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1057/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1057', 'id': 692511766, 'node_id': 'MDU6SXNzdWU2OTI1MTE3NjY=', 'number': 1057, 'title': 'Is this project abandoned?', 'user': {'login': 'tmigone', 'id': 3076185, 'node_id': 'MDQ6VXNlcjMwNzYxODU=', 'avatar_url': 'https://avatars1.githubusercontent.com/u/3076185?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tmigone', 'html_url': 'https://github.com/tmigone', 'followers_url': 'https://api.github.com/users/tmigone/followers', 'following_url': 'https://api.github.com/users/tmigone/following{/other_user}', 'gists_url': 'https://api.github.com/users/tmigone/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tmigone/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tmigone/subscriptions', 'organizations_url': 'https://api.github.com/users/tmigone/orgs', 'repos_url': 'https://api.github.com/users/tmigone/repos', 'events_url': 'https://api.github.com/users/tmigone/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tmigone/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2020-09-03T23:36:35Z', 'updated_at': '2020-09-03T23:43:08Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': \"Title, there doesn't seem to be a ton of updates, contributions/PR's not taken care of, and the examples don't really run. Any of the maintainers care to chime in?\", 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1056', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1056/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1056/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1056/events', 'html_url': 'https://github.com/dronekit/dronekit-python/pull/1056', 'id': 691749764, 'node_id': 'MDExOlB1bGxSZXF1ZXN0NDc4NDQ3MzMx', 'number': 1056, 'title': 'class CommandInt added', 'user': {'login': 'Zhigal', 'id': 31364070, 'node_id': 'MDQ6VXNlcjMxMzY0MDcw', 'avatar_url': 'https://avatars3.githubusercontent.com/u/31364070?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Zhigal', 'html_url': 'https://github.com/Zhigal', 'followers_url': 'https://api.github.com/users/Zhigal/followers', 'following_url': 'https://api.github.com/users/Zhigal/following{/other_user}', 'gists_url': 'https://api.github.com/users/Zhigal/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Zhigal/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Zhigal/subscriptions', 'organizations_url': 'https://api.github.com/users/Zhigal/orgs', 'repos_url': 'https://api.github.com/users/Zhigal/repos', 'events_url': 'https://api.github.com/users/Zhigal/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Zhigal/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-09-03T08:14:06Z', 'updated_at': '2020-09-03T08:14:06Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'pull_request': {'url': 'https://api.github.com/repos/dronekit/dronekit-python/pulls/1056', 'html_url': 'https://github.com/dronekit/dronekit-python/pull/1056', 'diff_url': 'https://github.com/dronekit/dronekit-python/pull/1056.diff', 'patch_url': 'https://github.com/dronekit/dronekit-python/pull/1056.patch'}, 'body': 'New class CommandInt added which allows to pass lat and lon parameters as integers to avoid float values rounding error', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1055', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1055/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1055/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1055/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1055', 'id': 688637268, 'node_id': 'MDU6SXNzdWU2ODg2MzcyNjg=', 'number': 1055, 'title': \"Can't connect pixhawk via 3DR telemetry( serial ) using dronekit\", 'user': {'login': 'amgaber95', 'id': 65262058, 'node_id': 'MDQ6VXNlcjY1MjYyMDU4', 'avatar_url': 'https://avatars2.githubusercontent.com/u/65262058?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/amgaber95', 'html_url': 'https://github.com/amgaber95', 'followers_url': 'https://api.github.com/users/amgaber95/followers', 'following_url': 'https://api.github.com/users/amgaber95/following{/other_user}', 'gists_url': 'https://api.github.com/users/amgaber95/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/amgaber95/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/amgaber95/subscriptions', 'organizations_url': 'https://api.github.com/users/amgaber95/orgs', 'repos_url': 'https://api.github.com/users/amgaber95/repos', 'events_url': 'https://api.github.com/users/amgaber95/events{/privacy}', 'received_events_url': 'https://api.github.com/users/amgaber95/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2020-08-30T02:08:18Z', 'updated_at': '2020-09-16T06:57:16Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'I am a newbie to dronekit. I have been trying to establish a connection between Pixhawk and my python script, however, it gives me this error:\\r\\nException in thread Thread-7:\\r\\nTraceback (most recent call last):\\r\\n  File \"C:\\\\ProgramData\\\\Anaconda3\\\\lib\\\\threading.py\", line 932, in _bootstrap_inner\\r\\n    self.run()\\r\\n  File \"C:\\\\ProgramData\\\\Anaconda3\\\\lib\\\\threading.py\", line 870, in run\\r\\n    self._target(*self._args, **self._kwargs)\\r\\n  File \"C:\\\\Users\\\\Abdelrahman\\\\.spyder-py3\\\\temp.py\", line 209, in loop\\r\\n    self.connect_my_copter()\\r\\n  File \"C:\\\\Users\\\\Abdelrahman\\\\.spyder-py3\\\\temp.py\", line 270, in connect_my_copter\\r\\n    self.vehicle = connect(self.connection_string,baud=57600, wait_ready=True)\\r\\n  File \"C:\\\\ProgramData\\\\Anaconda3\\\\lib\\\\site-packages\\\\dronekit\\\\__init__.py\", line 3170, in connect\\r\\n    vehicle.wait_ready(still_waiting_interval=still_waiting_interval,\\r\\n  File \"C:\\\\ProgramData\\\\Anaconda3\\\\lib\\\\site-packages\\\\dronekit\\\\__init__.py\", line 2374, in wait_ready\\r\\n    raise TimeoutError(\\'wait_ready experienced a timeout after %s seconds.\\' %\\r\\ndronekit.TimeoutError: wait_ready experienced a timeout after 30 seconds.\\r\\n\\r\\ntimeout error\\r\\n\\r\\nI am using port \"COM3\" that I connect my 3dr telemetry part to. \\r\\n\\r\\nusing this vehicle = connect(connection_string,baud=57600, wait_ready=True), although I managed to connect it through USB cable connect to Pixhawk and also successfully connect to Pixhawk and it works fine with a mission planner. Please help me, why I can\\'t connect to the drone using 3Dr telemetry. \\r\\n\\r\\n\\r\\n', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1054', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1054/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1054/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1054/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1054', 'id': 687031275, 'node_id': 'MDU6SXNzdWU2ODcwMzEyNzU=', 'number': 1054, 'title': 'Slow dronekit scripts', 'user': {'login': 'smiQi', 'id': 57180270, 'node_id': 'MDQ6VXNlcjU3MTgwMjcw', 'avatar_url': 'https://avatars0.githubusercontent.com/u/57180270?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/smiQi', 'html_url': 'https://github.com/smiQi', 'followers_url': 'https://api.github.com/users/smiQi/followers', 'following_url': 'https://api.github.com/users/smiQi/following{/other_user}', 'gists_url': 'https://api.github.com/users/smiQi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/smiQi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/smiQi/subscriptions', 'organizations_url': 'https://api.github.com/users/smiQi/orgs', 'repos_url': 'https://api.github.com/users/smiQi/repos', 'events_url': 'https://api.github.com/users/smiQi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/smiQi/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-08-27T07:58:36Z', 'updated_at': '2020-08-27T07:58:36Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Hi,\\r\\ni connected my Pi4 to my APM via MicroUsb. Everything works fine but a simple dronekit script takes like 15 seconds to finish? Can i do something so i make things faster?\\r\\nWith MissionPlanner everything is at normal speed.\\r\\n\\r\\nCan anyone help me?\\r\\n\\r\\nThanks and regards\\r\\nSimon', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1053', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1053/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1053/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1053/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1053', 'id': 686763665, 'node_id': 'MDU6SXNzdWU2ODY3NjM2NjU=', 'number': 1053, 'title': 'set waypoints for guided_mode from a companion pc and return back to auto_mode? ', 'user': {'login': 'Mytre', 'id': 35982669, 'node_id': 'MDQ6VXNlcjM1OTgyNjY5', 'avatar_url': 'https://avatars3.githubusercontent.com/u/35982669?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Mytre', 'html_url': 'https://github.com/Mytre', 'followers_url': 'https://api.github.com/users/Mytre/followers', 'following_url': 'https://api.github.com/users/Mytre/following{/other_user}', 'gists_url': 'https://api.github.com/users/Mytre/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Mytre/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Mytre/subscriptions', 'organizations_url': 'https://api.github.com/users/Mytre/orgs', 'repos_url': 'https://api.github.com/users/Mytre/repos', 'events_url': 'https://api.github.com/users/Mytre/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Mytre/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 2, 'created_at': '2020-08-26T23:06:08Z', 'updated_at': '2020-09-08T20:48:17Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'A complete change on this question since I was able to further on my code.  I have not seen an example of this or on the documentation, is it possible to take the drone out of auto_mode to guided_mode with specific waypoints, and then return back to auto_mode ? without restarting the waypoints from auto_mode.  The goal of this would be an example of a script running that based on a sensor would set up a small guided_mode set of waypoints, interrupt auto_mode, then return to auto_mode and continue to the next waypoints in auto_mode.\\r\\n\\r\\n', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1052', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1052/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1052/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1052/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1052', 'id': 686179635, 'node_id': 'MDU6SXNzdWU2ODYxNzk2MzU=', 'number': 1052, 'title': 'is autocopter 4.0.3 supported?', 'user': {'login': 'addriumruss', 'id': 35988105, 'node_id': 'MDQ6VXNlcjM1OTg4MTA1', 'avatar_url': 'https://avatars1.githubusercontent.com/u/35988105?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/addriumruss', 'html_url': 'https://github.com/addriumruss', 'followers_url': 'https://api.github.com/users/addriumruss/followers', 'following_url': 'https://api.github.com/users/addriumruss/following{/other_user}', 'gists_url': 'https://api.github.com/users/addriumruss/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/addriumruss/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/addriumruss/subscriptions', 'organizations_url': 'https://api.github.com/users/addriumruss/orgs', 'repos_url': 'https://api.github.com/users/addriumruss/repos', 'events_url': 'https://api.github.com/users/addriumruss/events{/privacy}', 'received_events_url': 'https://api.github.com/users/addriumruss/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-08-26T09:47:50Z', 'updated_at': '2020-08-26T09:47:50Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': '', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1051', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1051/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1051/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1051/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1051', 'id': 683359523, 'node_id': 'MDU6SXNzdWU2ODMzNTk1MjM=', 'number': 1051, 'title': 'Gimbal rotate() has no effect (testing with SITL virtual gimbal)', 'user': {'login': 'hhackbarth', 'id': 8024018, 'node_id': 'MDQ6VXNlcjgwMjQwMTg=', 'avatar_url': 'https://avatars2.githubusercontent.com/u/8024018?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/hhackbarth', 'html_url': 'https://github.com/hhackbarth', 'followers_url': 'https://api.github.com/users/hhackbarth/followers', 'following_url': 'https://api.github.com/users/hhackbarth/following{/other_user}', 'gists_url': 'https://api.github.com/users/hhackbarth/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/hhackbarth/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/hhackbarth/subscriptions', 'organizations_url': 'https://api.github.com/users/hhackbarth/orgs', 'repos_url': 'https://api.github.com/users/hhackbarth/repos', 'events_url': 'https://api.github.com/users/hhackbarth/events{/privacy}', 'received_events_url': 'https://api.github.com/users/hhackbarth/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-08-21T07:24:50Z', 'updated_at': '2020-08-21T07:24:50Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': \"I am testing gimbal control - at the moment only with Mission Planner running SITL (ArduCopter 4.1.0-dev).\\r\\n\\r\\nVirtual gimbal is configured:\\r\\nMNT_TYPE = 3 (AlexMos Serial)\\r\\n\\r\\nAdding a listener to gimbal attribute shows, that gimbal status messages are generated (pitch: 0, roll: 0, yaw: 0).\\r\\n\\r\\nSending a command like:\\r\\n\\r\\n                vehicle.gimbal.rotate(40, 0, 0)\\r\\n\\r\\nhas no effect, gimbal still reports pitch: 0.\\r\\n\\r\\nAny idea what's goning wrong here?\", 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1050', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1050/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1050/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1050/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1050', 'id': 682818810, 'node_id': 'MDU6SXNzdWU2ODI4MTg4MTA=', 'number': 1050, 'title': 'How to run two Dronekit scripts for one vehicle?', 'user': {'login': 'cnpcshangbo', 'id': 4831029, 'node_id': 'MDQ6VXNlcjQ4MzEwMjk=', 'avatar_url': 'https://avatars0.githubusercontent.com/u/4831029?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/cnpcshangbo', 'html_url': 'https://github.com/cnpcshangbo', 'followers_url': 'https://api.github.com/users/cnpcshangbo/followers', 'following_url': 'https://api.github.com/users/cnpcshangbo/following{/other_user}', 'gists_url': 'https://api.github.com/users/cnpcshangbo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/cnpcshangbo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/cnpcshangbo/subscriptions', 'organizations_url': 'https://api.github.com/users/cnpcshangbo/orgs', 'repos_url': 'https://api.github.com/users/cnpcshangbo/repos', 'events_url': 'https://api.github.com/users/cnpcshangbo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/cnpcshangbo/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-08-20T15:34:13Z', 'updated_at': '2020-08-20T15:34:13Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'I want to run two Dronekit scripts for one vehicle. \\r\\nOne script is forwarding vision positional estimation data from RealSense T265 to ArduPilot to reduce drift for non-GPS environment. \\r\\nhttps://github.com/thien94/vision_to_mavros/blob/master/scripts/t265_to_mavlink.py\\r\\n\\r\\nThe other script is processing depth images and sending velocity commands to guide the vehicle. \\r\\nhttps://github.com/dronedojo/droneProgrammingCourse/blob/master/dk/velocity_based_movement.py\\r\\n\\r\\nI used MavProxy to forward a serial port to two IP ports for the two scripts.\\r\\nTheoretically, they are sending two types of messages and they should work together. However, I found that the velocity script keeps waiting for the vehicle to become armable.\\r\\n![image](https://user-images.githubusercontent.com/4831029/90792263-e0739400-e2cf-11ea-8b3e-b84be5d8441d.png)\\r\\n\\r\\nI am thinking of some possible solutions.\\r\\n1. Change the velocity script to disable the arming check;\\r\\n2. Merge the two scripts into one script, however, they have different loop logic.\\r\\n\\r\\nIs there somebody who has used two Dronekit scripts together? Hope to get some suggestions.\\r\\nThanks,\\r\\n@cnpcshangbo\\r\\n', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1049', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1049/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1049/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1049/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1049', 'id': 680892253, 'node_id': 'MDU6SXNzdWU2ODA4OTIyNTM=', 'number': 1049, 'title': 'How to know when the drone is at the requested location...', 'user': {'login': 'The1only', 'id': 6682924, 'node_id': 'MDQ6VXNlcjY2ODI5MjQ=', 'avatar_url': 'https://avatars2.githubusercontent.com/u/6682924?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/The1only', 'html_url': 'https://github.com/The1only', 'followers_url': 'https://api.github.com/users/The1only/followers', 'following_url': 'https://api.github.com/users/The1only/following{/other_user}', 'gists_url': 'https://api.github.com/users/The1only/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/The1only/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/The1only/subscriptions', 'organizations_url': 'https://api.github.com/users/The1only/orgs', 'repos_url': 'https://api.github.com/users/The1only/repos', 'events_url': 'https://api.github.com/users/The1only/events{/privacy}', 'received_events_url': 'https://api.github.com/users/The1only/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-08-18T10:22:55Z', 'updated_at': '2020-08-18T10:23:10Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'If I issue a GOTO or send a \" msg = self.vehicle.message_factory.set_position_target_global_int_encode(\\r\\n            0, 0, 0, \\r\\n            mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT,  \\r\\n            0b0000101111111000, \\r\\n            int(x*10000000), int(y*10000000), float(z), \\r\\n            0,0,0,  \\r\\n            0, 0, 0,  \\r\\n            float(yaw), 0) \"\\r\\n\\r\\nHOW DO I KNOW WHEN I AM THERE????\\r\\n\\r\\nIn RosettaDrone II the system changes its mode to AUTO while mowing and then back to GUIDED when at position...\\r\\nThis I can wait for in DroneKit. \\r\\nBut how do you/mavlink do this????', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1048', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1048/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1048/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1048/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1048', 'id': 680220185, 'node_id': 'MDU6SXNzdWU2ODAyMjAxODU=', 'number': 1048, 'title': 'connect() hangs with no info why on Cube Orange', 'user': {'login': 'siadajpan', 'id': 6299154, 'node_id': 'MDQ6VXNlcjYyOTkxNTQ=', 'avatar_url': 'https://avatars2.githubusercontent.com/u/6299154?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/siadajpan', 'html_url': 'https://github.com/siadajpan', 'followers_url': 'https://api.github.com/users/siadajpan/followers', 'following_url': 'https://api.github.com/users/siadajpan/following{/other_user}', 'gists_url': 'https://api.github.com/users/siadajpan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/siadajpan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/siadajpan/subscriptions', 'organizations_url': 'https://api.github.com/users/siadajpan/orgs', 'repos_url': 'https://api.github.com/users/siadajpan/repos', 'events_url': 'https://api.github.com/users/siadajpan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/siadajpan/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 2, 'created_at': '2020-08-17T13:04:38Z', 'updated_at': '2020-08-18T08:30:05Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': \"I'm running dronekit on NVIDIA Jetson Nano connecting through UART with Pixhawk Cube Orange.\\r\\ndronekit version = 2.9.2\\r\\npymavlink version = 2.4.9\\r\\npython version = 3.6.9\\r\\n\\r\\nAfter running ```mavproxy.py --master=/dev/ttyTHS1 --baudrate=115200```\\r\\nI'm getting:\\r\\n```\\r\\nConnect /dev/ttyTHS1 source_system=255\\r\\nLog Directory:\\r\\nTelemetry log: mav.tlog\\r\\nWaiting for heartbeat from /dev/ttyTHS1\\r\\nMAV> online system 1\\r\\nSTABILIZE> Mode STABILIZE\\r\\n```\\r\\nbut after running \\r\\n```\\r\\n>>> import dronekit\\r\\n>>> v = dronekit.connect('/dev/ttyTHS1', baud=115200)\\r\\n```\\r\\nIt hangs without showing anything more (not even heartbeat timeout), so it seems like heartbeat is present.\\r\\nI can see the some incoming messages every second after running ```screen /dev/ttyTHS1```. I was also trying to set flag wait_ready to False, but without success.\", 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1047', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1047/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1047/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1047/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1047', 'id': 675121740, 'node_id': 'MDU6SXNzdWU2NzUxMjE3NDA=', 'number': 1047, 'title': 'wait_ready experienced an error after 30 seconds', 'user': {'login': 'RomulusSam', 'id': 66646529, 'node_id': 'MDQ6VXNlcjY2NjQ2NTI5', 'avatar_url': 'https://avatars2.githubusercontent.com/u/66646529?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/RomulusSam', 'html_url': 'https://github.com/RomulusSam', 'followers_url': 'https://api.github.com/users/RomulusSam/followers', 'following_url': 'https://api.github.com/users/RomulusSam/following{/other_user}', 'gists_url': 'https://api.github.com/users/RomulusSam/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/RomulusSam/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/RomulusSam/subscriptions', 'organizations_url': 'https://api.github.com/users/RomulusSam/orgs', 'repos_url': 'https://api.github.com/users/RomulusSam/repos', 'events_url': 'https://api.github.com/users/RomulusSam/events{/privacy}', 'received_events_url': 'https://api.github.com/users/RomulusSam/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2020-08-07T16:16:07Z', 'updated_at': '2020-08-30T01:59:30Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'Hi dronekit!\\r\\n\\r\\nI\\'m trying (and failing) to connect to my drone through ttyTHS1, and I\\'m pretty sure that\\'s the correct port since I tried ttyTHS2 and instantly wasn\\'t able to connect. I\\'m baffled by this error since last week I was able to connect just fine using the same commands I am using now: vehicle = connect(\\'/dev/ttyTHS1\\', wait_ready=True, baud=57600). Whenever I try to connect, after a short period of nothing, I am given the error \"dronekit.TimeoutError wait_ready experienced an error after 30 seconds\".\\r\\n\\r\\nIs there anything else that I didn\\'t check that I don\\'t know about? I\\'m lost at sea here and could use any help anyone has to offer. Let me know if you need any other info too and I can supply it.\\r\\n\\r\\nMuch appreciated,\\r\\nSam\\r\\n', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1046', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1046/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1046/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1046/events', 'html_url': 'https://github.com/dronekit/dronekit-python/pull/1046', 'id': 667583215, 'node_id': 'MDExOlB1bGxSZXF1ZXN0NDU4MjIyMDY2', 'number': 1046, 'title': 'Channels: fix wrong key type', 'user': {'login': 'tajisoft', 'id': 22985371, 'node_id': 'MDQ6VXNlcjIyOTg1Mzcx', 'avatar_url': 'https://avatars1.githubusercontent.com/u/22985371?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tajisoft', 'html_url': 'https://github.com/tajisoft', 'followers_url': 'https://api.github.com/users/tajisoft/followers', 'following_url': 'https://api.github.com/users/tajisoft/following{/other_user}', 'gists_url': 'https://api.github.com/users/tajisoft/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tajisoft/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tajisoft/subscriptions', 'organizations_url': 'https://api.github.com/users/tajisoft/orgs', 'repos_url': 'https://api.github.com/users/tajisoft/repos', 'events_url': 'https://api.github.com/users/tajisoft/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tajisoft/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-07-29T06:21:00Z', 'updated_at': '2020-07-29T06:21:00Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'pull_request': {'url': 'https://api.github.com/repos/dronekit/dronekit-python/pulls/1046', 'html_url': 'https://github.com/dronekit/dronekit-python/pull/1046', 'diff_url': 'https://github.com/dronekit/dronekit-python/pull/1046.diff', 'patch_url': 'https://github.com/dronekit/dronekit-python/pull/1046.patch'}, 'body': 'It returns None in all channel because of wrong key type.\\r\\n```\\r\\nvehicle = connect(\"127.0.0.1:14550\", wait_ready=True)\\r\\nvehcie.channels\\r\\n{\\'1\\': None, \\'2\\': None, \\'3\\': None, \\'4\\': None, \\'5\\': None, \\'6\\': None, \\'7\\': None, \\'8\\': None}\\r\\n```', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1044', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1044/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1044/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1044/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1044', 'id': 665169068, 'node_id': 'MDU6SXNzdWU2NjUxNjkwNjg=', 'number': 1044, 'title': 'Guided Mode Movement and Commands for FIXED-WINGS', 'user': {'login': 'Ayvazof', 'id': 40017500, 'node_id': 'MDQ6VXNlcjQwMDE3NTAw', 'avatar_url': 'https://avatars2.githubusercontent.com/u/40017500?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Ayvazof', 'html_url': 'https://github.com/Ayvazof', 'followers_url': 'https://api.github.com/users/Ayvazof/followers', 'following_url': 'https://api.github.com/users/Ayvazof/following{/other_user}', 'gists_url': 'https://api.github.com/users/Ayvazof/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Ayvazof/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Ayvazof/subscriptions', 'organizations_url': 'https://api.github.com/users/Ayvazof/orgs', 'repos_url': 'https://api.github.com/users/Ayvazof/repos', 'events_url': 'https://api.github.com/users/Ayvazof/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Ayvazof/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-07-24T13:28:00Z', 'updated_at': '2020-07-24T13:52:40Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'The issue is that, that I need to control plane from script depending of external sensor only way I found is use RC OVERRIDE but it is not a good way how I understand. Is there some way do it right?\\r\\nThanks in advance', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1043', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1043/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1043/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1043/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1043', 'id': 664136701, 'node_id': 'MDU6SXNzdWU2NjQxMzY3MDE=', 'number': 1043, 'title': 'Python script taking a long time to arm.', 'user': {'login': 'ryanjc97', 'id': 22802811, 'node_id': 'MDQ6VXNlcjIyODAyODEx', 'avatar_url': 'https://avatars1.githubusercontent.com/u/22802811?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ryanjc97', 'html_url': 'https://github.com/ryanjc97', 'followers_url': 'https://api.github.com/users/ryanjc97/followers', 'following_url': 'https://api.github.com/users/ryanjc97/following{/other_user}', 'gists_url': 'https://api.github.com/users/ryanjc97/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ryanjc97/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ryanjc97/subscriptions', 'organizations_url': 'https://api.github.com/users/ryanjc97/orgs', 'repos_url': 'https://api.github.com/users/ryanjc97/repos', 'events_url': 'https://api.github.com/users/ryanjc97/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ryanjc97/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2020-07-23T01:00:26Z', 'updated_at': '2020-08-07T19:25:06Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': \"I have written a basic autopilot script for my drone, and the SITL simulation works perfectly fine, but I run into some issues on the physical hardware. When I first start up my system, it takes a very long time to become armable, somewhere around 10 minutes. If I just take out the line of code that waits for \\nis_armable to be true, I get GPS speed errors. I can't seem to find a workaround for the GPS speed errors or the obnoxiously long arming time. I am using a raspberry pi 3 and a pixhawk if that makes a difference.\", 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1042', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1042/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1042/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1042/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1042', 'id': 656206080, 'node_id': 'MDU6SXNzdWU2NTYyMDYwODA=', 'number': 1042, 'title': 'Airsim/Ardupilot Listeners for sensor data ', 'user': {'login': 'mgroov', 'id': 44854053, 'node_id': 'MDQ6VXNlcjQ0ODU0MDUz', 'avatar_url': 'https://avatars3.githubusercontent.com/u/44854053?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mgroov', 'html_url': 'https://github.com/mgroov', 'followers_url': 'https://api.github.com/users/mgroov/followers', 'following_url': 'https://api.github.com/users/mgroov/following{/other_user}', 'gists_url': 'https://api.github.com/users/mgroov/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mgroov/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mgroov/subscriptions', 'organizations_url': 'https://api.github.com/users/mgroov/orgs', 'repos_url': 'https://api.github.com/users/mgroov/repos', 'events_url': 'https://api.github.com/users/mgroov/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mgroov/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2020-07-13T23:04:35Z', 'updated_at': '2020-07-13T23:04:35Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'body': 'I am currently working on a windows wsl 18.04 with dronekit and ardupilot looking at an air sim sitl. I can use the script to have the drone take off and land with proper altitude readings. However, I cannot get the * message \\r\\nlistener to print anything at all as well as a rangefinder despite one being defined in the settings.json. \\r\\n\\r\\nDronekit version:2.9.2\\r\\n\\r\\n\\r\\nThe script I am using:\\r\\n```python\\r\\nimport dronekit\\r\\nimport pymavlink\\r\\nfrom dronekit import connect,VehicleMode\\r\\nimport time\\r\\n\\r\\n\\r\\n\\r\\n# Connect to the Vehicle (in this case a simulator running the same computer)\\r\\nvehicle = connect(\\'127.0.0.1:14550\\', wait_ready=True)\\r\\n\\r\\n@vehicle.on_message(\\'*\\')\\r\\ndef listener(self, name, message):\\r\\n    print (\\'message: %s\\' % message)\\r\\n    print (\\'potato\\')\\r\\n\\r\\nprint (\"Mode: %s\" % vehicle.mode.name )   # settable\\r\\n\\r\\n#Create a message listener using the decorator.\\r\\n@vehicle.on_message(\\'LIDAR\\')\\r\\ndef listener(self, name, message):\\r\\n    print ( \\'message: %s\\' % message)\\r\\n    print (\\'have fun at boss fight\\')\\r\\n\\r\\ndef arm_and_takeoff(aTargetAltitude):\\r\\n    \"\"\"\\r\\n    Arms vehicle and fly to aTargetAltitude.\\r\\n    \"\"\"\\r\\n\\r\\n    print (\"Basic pre-arm checks\")\\r\\n    # Don\\'t try to arm until autopilot is ready\\r\\n    while not vehicle.is_armable:\\r\\n        print (\" Waiting for vehicle to initialise...\")\\r\\n        time.sleep(1)\\r\\n\\r\\n    print (\"Arming motors\")\\r\\n    # Copter should arm in GUIDED mode\\r\\n    vehicle.mode    = VehicleMode(\"GUIDED\")\\r\\n    vehicle.armed   = True\\r\\n\\r\\n    # Confirm vehicle armed before attempting to take off\\r\\n    while not vehicle.armed:\\r\\n        print (\" Waiting for arming...\")\\r\\n        time.sleep(1)\\r\\n\\r\\n    print (\"Taking off!\")\\r\\n    vehicle.simple_takeoff(aTargetAltitude) # Take off to target altitude\\r\\n\\r\\n    # Wait until the vehicle reaches a safe height before processing the goto (otherwise the command\\r\\n    #  after Vehicle.simple_takeoff will execute immediately).\\r\\n    while True:\\r\\n        print (\" Altitude: \", vehicle.location.global_relative_frame.alt)\\r\\n        #Break and return from function just below target altitude.\\r\\n        if vehicle.location.global_relative_frame.alt>=aTargetAltitude*0.95:\\r\\n            print (\"Reached target altitude\")\\r\\n            break\\r\\n        time.sleep(1)\\r\\n\\r\\narm_and_takeoff(20)\\r\\ntime.sleep(10)\\r\\nvehicle.mode    = VehicleMode(\"LAND\")\\r\\ntime.sleep(5)\\r\\narm_and_takeoff(10)\\r\\ntime.sleep(1)\\r\\nvehicle.mode = VehicleMode(\"LAND\")\\r\\n\\r\\nvehicle.remove_message_listener();\\r\\n```\\r\\n\\r\\nThe settings file:\\r\\n```json\\r\\n\\r\\n{\\r\\n  \"SettingsVersion\": 1.2,\\r\\n  \"SimMode\": \"Multirotor\",\\r\\n  \"OriginGeopoint\": {\\r\\n    \"Latitude\": -35.363261,\\r\\n    \"Longitude\": 149.165230,\\r\\n    \"Altitude\": 583\\r\\n  },\\r\\n  \"Vehicles\": {\\r\\n    \"Copter\": {\\r\\n      \"VehicleType\": \"ArduCopter\",\\r\\n      \"UseSerial\": false,\\r\\n      \"LocalHostIp\": \"127.0.0.1\",\\r\\n      \"UdpIp\": \"127.0.0.1\",\\r\\n      \"UdpPort\": 9003,\\r\\n      \"ControlPort\": 9002,\\r\\n      \"AutoCreate\": true,\\r\\n      \"Sensors\": {\\r\\n        \"Imu\": {\\r\\n          \"SensorType\": 2,\\r\\n          \"Enabled\": true\\r\\n        },\\r\\n        \"Gps\": {\\r\\n          \"SensorType\": 3,\\r\\n          \"Enabled\": true\\r\\n        },\\r\\n        \"Lidar1\": {\\r\\n          \"SensorType\": 6,\\r\\n          \"Enabled\": true,\\r\\n          \"NumberOfChannels\": 1,\\r\\n          \"PointsPerSecond\": 5000,\\r\\n          \"DrawDebugPoints\": false,\\r\\n          \"RotationsPerSecond\": 10,\\r\\n          \"VerticalFOVUpper\": 0,\\r\\n          \"VerticalFOVLower\": 0,\\r\\n          \"HorizontalFOVStart\": 0,\\r\\n          \"HorizontalFOVEnd\": 0,\\r\\n          \"DataFrame\": \"SensorLocalFrame\"\\r\\n        },\\r\\n        \"Distance\": {\\r\\n          \"SensorType\": 5,\\r\\n          \"Enabled\": true\\r\\n        }\\r\\n      }\\r\\n    }\\r\\n  }\\r\\n}\\r\\n```\\r\\nThe command I use to launch ardupilot:\\r\\n```\\r\\nsim_vehicle.py -v ArduCopter -f airsim-copter --add-param-file=libraries/SITL/examples/Airsim/lidar.parm  --console --map\\r\\n```', 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1041', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1041/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1041/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1041/events', 'html_url': 'https://github.com/dronekit/dronekit-python/issues/1041', 'id': 650930855, 'node_id': 'MDU6SXNzdWU2NTA5MzA4NTU=', 'number': 1041, 'title': 'SITL test is failing: copter mode stuck on STABILIZE', 'user': {'login': 'pietrodn', 'id': 5058646, 'node_id': 'MDQ6VXNlcjUwNTg2NDY=', 'avatar_url': 'https://avatars3.githubusercontent.com/u/5058646?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/pietrodn', 'html_url': 'https://github.com/pietrodn', 'followers_url': 'https://api.github.com/users/pietrodn/followers', 'following_url': 'https://api.github.com/users/pietrodn/following{/other_user}', 'gists_url': 'https://api.github.com/users/pietrodn/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/pietrodn/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/pietrodn/subscriptions', 'organizations_url': 'https://api.github.com/users/pietrodn/orgs', 'repos_url': 'https://api.github.com/users/pietrodn/repos', 'events_url': 'https://api.github.com/users/pietrodn/events{/privacy}', 'received_events_url': 'https://api.github.com/users/pietrodn/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 8, 'created_at': '2020-07-04T17:51:47Z', 'updated_at': '2020-07-20T13:41:03Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'active_lock_reason': None, 'body': \"The SITL tests are currently failing on the master branch, both for [Python 2](https://app.circleci.com/pipelines/github/dronekit/dronekit-python/1/workflows/05098a02-aef1-4dc0-94ae-c93331c254a4/jobs/1418/steps) and [Python 3](https://app.circleci.com/pipelines/github/dronekit/dronekit-python/1/workflows/05098a02-aef1-4dc0-94ae-c93331c254a4/jobs/1419/steps).\\r\\nThe cause is a SITL test that's not passing: [test_goto.py](https://github.com/dronekit/dronekit-python/blob/master/dronekit/test/sitl/test_goto.py).\\r\\n\\r\\nThe apparent reason of the error is that the test times out when setting the mode to `GUIDED`.\\r\\nI managed to run the unit test locally, and I can't get the SITL to switch to `GUIDED`: the vehicle remains stuck on `STABILIZE`. The GPS and the global location seem to be ok. The Vehicle is periodically receiving heartbeat updates containing the mode flag, so it's not a reception problem.\\r\\n\\r\\nMy hypothesis is that some update on the ArduPilot side, or in some dependencies, made the tests fail. From the [commit history](https://github.com/dronekit/dronekit-python/commits/master) it's easy to see that the previous commits (that worked) are identical to the latest ones, which were simple documentation changes.\\r\\n\\r\\nAny hints?\\r\\n\\r\\n\", 'performed_via_github_app': None}, {'url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1039', 'repository_url': 'https://api.github.com/repos/dronekit/dronekit-python', 'labels_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1039/labels{/name}', 'comments_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1039/comments', 'events_url': 'https://api.github.com/repos/dronekit/dronekit-python/issues/1039/events', 'html_url': 'https://github.com/dronekit/dronekit-python/pull/1039', 'id': 646034387, 'node_id': 'MDExOlB1bGxSZXF1ZXN0NDQwNDAxNzQz', 'number': 1039, 'title': 'Mission download protocol implementation', 'user': {'login': 'eminakgun', 'id': 55315177, 'node_id': 'MDQ6VXNlcjU1MzE1MTc3', 'avatar_url': 'https://avatars2.githubusercontent.com/u/55315177?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/eminakgun', 'html_url': 'https://github.com/eminakgun', 'followers_url': 'https://api.github.com/users/eminakgun/followers', 'following_url': 'https://api.github.com/users/eminakgun/following{/other_user}', 'gists_url': 'https://api.github.com/users/eminakgun/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/eminakgun/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/eminakgun/subscriptions', 'organizations_url': 'https://api.github.com/users/eminakgun/orgs', 'repos_url': 'https://api.github.com/users/eminakgun/repos', 'events_url': 'https://api.github.com/users/eminakgun/events{/privacy}', 'received_events_url': 'https://api.github.com/users/eminakgun/received_events', 'type': 'User', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2020-06-26T06:12:36Z', 'updated_at': '2020-08-21T17:30:35Z', 'closed_at': None, 'author_association': 'NONE', 'active_lock_reason': None, 'pull_request': {'url': 'https://api.github.com/repos/dronekit/dronekit-python/pulls/1039', 'html_url': 'https://github.com/dronekit/dronekit-python/pull/1039', 'diff_url': 'https://github.com/dronekit/dronekit-python/pull/1039.diff', 'patch_url': 'https://github.com/dronekit/dronekit-python/pull/1039.patch'}, 'body': 'This implements mission download properly by checking timeout of 500msecs in each request and re-requesting the whole mission or next item. Tested in SITL and real hardware running ArduPlane 3.9.11.', 'performed_via_github_app': None}]\n"
     ]
    }
   ],
   "source": [
    "url = \"http://api.github.com/repos/\" + OWNER + \"/\" + REPO + \"/issues\"\n",
    "\n",
    "response = requests.post(url)\n",
    "    \n",
    "if (response != None) & (response.status_code == 200): \n",
    "    re = response.json()\n",
    "    print('success!')\n",
    "    print(re)\n",
    "    \n",
    "else:\n",
    "    print(response.status_code)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
